// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// biome-ignore lint/correctness/noUnusedVariables: <explanation>
type Env = {
  LINE_USER_ID: string;
  LINE_CHANNEL_ACCESS_TOKEN: string;
  NOTION_API_KEY: string;
  GITHUB_TOKEN: string;
  BLOG_WORKER: R2Bucket;
  R2_PUBLIC_URL: string;
};
